[workspace]
authors = ["ethanc8 <echaroenpitaks@gmail.com>"]
channels = ["conda-forge"]
name = "RebuiltTrajOpt"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"

[pypi-dependencies]
sleipnirgroup-jormungandr = ">=0.3.4, <0.4"
